version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ClaimProcess"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-16wl6ve1sk30w"
s3_prefix = "ClaimProcess"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
