version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ClaimWorkFlow"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1hcqd4ms0bhpa"
s3_prefix = "ClaimWorkFlow"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
